name: CI

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]

jobs:
  python:
    name: Python Lint and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff black isort pytest
      - name: Ruff Lint
        run: ruff check .
      - name: Black Check
        run: black --check .
      # isort check removed
      - name: Run Pytest
        env:
          PYTHONPATH: .
        run: pytest -q

  web:
    name: Web Lint and Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Lint (ESLint)
        run: npm run lint
      - name: Format (Prettier check)
        run: npm run format
      - name: Run unit tests (Vitest)
        run: npm test
